apiVersion: v1
kind: Pod
metadata:
  name: db-client
  namespace: troubleshoot-app
spec:
  initContainers:
    - name: wait-for-db
      image: busybox:latest
      command:
        - sh
        - -c
        - "until nc -z -w 2 database-service 5432; do echo wait; sleep 2; done"
  containers:
    - name: client
      image: busybox:latest
      command: ["sh", "-c", "echo Connected to DB && sleep 3600"]
