apiVersion: v1
kind: Pod
metadata:
  name: health-failing
  namespace: troubleshoot-app
spec:
  containers:
    - image: nginx:alpine
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /
          port: 80
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 3
        successThreshold: 1
        timeoutSeconds: 1
      name: web
      resources: {}
      volumeMounts:
        - mountPath: /usr/share/nginx/html/healthz
          name: health-vol
          readOnly: true
  restartPolicy: Always
  volumes:
    - name: health-vol
      emptyDir: {}
