resources:
  - ../../base
namespace: production
namePrefix: prod-
labels:
  - pairs:
      env: production
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: web-app
    path: patch.yaml
