apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  finalizers:
    - kubernetes.io/pvc-protection
  name: pvc-broken-match
  namespace: storage-troubleshoot-lab
  resourceVersion: "202144"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual-trouble
  volumeMode: Filesystem
status: {}
