apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dynamic
  namespace: storage-lab
spec:
  storageClassName: sc-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---

