apiVersion: v1
kind: Pod
metadata:
  labels:
    run: writer-pod
  name: writer-pod
  namespace: storage-lab
spec:
  volumes:
    - name: pvc-shared-volume
      persistentVolumeClaim:
        claimName: pvc-shared
  containers:
    - command:
        - sh
        - -c
        - while true; do date >> /data/shared/status.log; sleep 1; done
      image: busybox:latest
      name: writer-pod
      resources: {}
      volumeMounts:
        - mountPath: "/data/shared"
          name: pvc-shared-volume

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
