apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busy-worker
  name: busy-worker
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: busy-worker
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
