apiVersion: v1
kind: Pod
metadata:
  labels:
    run: control-watchdog
  name: control-watchdog
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: busybox
      name: control-watchdog
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
