apiVersion: v1
kind: Pod
metadata:
  labels:
    run: db-backend
  name: db-backend
spec:
  nodeSelector:
    diskType: ssd
  containers:
    - image: redis:alpine
      name: db-backend
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
